### ISSUE TITLE
style is not applied

### ISSUE THREAD

**Issue by sotayamashita** [sindresorhus/github-hide-files#11]
github-hide-files button's style is not applied. Here is capture image below:

![screen shot 2015-05-14 at 16 02 21](https://cloud.githubusercontent.com/assets/1587053/7627471/a9ffebc8-fa52-11e4-8348-c2c17b2d4d86.png)

I am trying to know what is cause of problem and fix it.

**Comment by arthurvr** [comment]
Which style does not work? Please be a little more specific.

**Comment by sotayamashita** [comment]
I am talking about `content.css`. In this CSS, you use table selector but Github is not use table tag anymore so I think we have to write new CSS.

**Comment by sotayamashita** [comment]
@arthurvr Is this button style working in your browser ?

**Comment by sotayamashita** [comment]
I create a PR. https://github.com/sindresorhus/github-hide-files/pull/12

**Comment by arthurvr** [comment]
Closing as this is fixed in https://github.com/sindresorhus/github-hide-files/pull/12.
