### ISSUE TITLE
Change toggle button to say "hide" or "show"

### ISSUE THREAD

**Issue by ArtskydJ** [sindresorhus/github-hide-files#13]
What do you think of the **`Toggle Dotfiles`** button toggling between **`Show Dotfiles`** or **`Hide Dotfiles`**, depending on if they're being shown or hidden?

One reason for this, is if a project has no dotfiles, and you click **`Toggle Dotfiles`**, then nothing happens; you're not sure if you missed the button, or if it's not working, before you realize that there are no dotfiles.

Thoughts?

**Comment by sindresorhus** [comment]
Yes! I wanted to do that initially but was too lazy...

Interested in doing a pull request? :)
