### ISSUE TITLE
Disable on repos named "dotfiles"

### ISSUE THREAD

**Issue by paulirish** [sindresorhus/github-hide-files#14]
Because that's what you're there for. :)

**Comment by sindresorhus** [comment]
I'm already doing that: https://github.com/sindresorhus/github-hide-files/blob/3de64679e2dc0a9357d7ef19bd62d013d6cd4431/content.js#L53, but some GitHub change seems to have broken it.

**Comment by paulirish** [comment]
ah interesting.

yeah @kevva's pr looks solid.
