### ISSUE TITLE
What would be the use of hiding files in a repo?

### ISSUE THREAD

**Issue by koenpunt** [sindresorhus/github-hide-files#17]
I understand some people see the use of it, but I think hiding files in a repo is asking for problems.

Or am I missing something here?

Don't take me wrong, I'm not trying to be negative, I just want to understand :)

**Comment by sindresorhus** [comment]
I was tired of seeing so many dotfiles in every repo I visit and I almost never look at them. So I decided to make this extension to make it easier to spot the files I actually care about. You can easily toggle the visibility of the dotfiles with the "Toggle dotfiles" button. If you have to ask this question you probably don't need this.

**Comment by koenpunt** [comment]
> If you have to ask this question you probably don't need this.

Probably true :)

Although I feel for "dimming" the dotfiles, but that feature hasn't landed, right?

**Comment by sindresorhus** [comment]
> Although I feel for "dimming" the dotfiles, but that feature hasn't landed, right?

No, I don't need it, but PR welcome if you want it.
