### ISSUE TITLE
Modifications due to GitHub's new look

### ISSUE THREAD

**Issue by harshasrinivas** [sindresorhus/github-hide-files#18]
![dotfiles](https://cloud.githubusercontent.com/assets/7846363/11282092/95b2e9ac-8f23-11e5-95cf-4a6381afaa36.png)

Since GitHub have released a [new look for repositories](https://github.com/blog/2085-a-new-look-for-repositories). The positioning of **Show Dotfiles** button could be modified.

**Comment by sindresorhus** [comment]
I don't have the new look yet and probably won't get to this any time soon, so a PR would be much appreciated :)
